services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: chatbotdb
      POSTGRES_USER: chatbotuser
      POSTGRES_PASSWORD: chatbotpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatbot_network

  web:
    build: .
    container_name: django_chatbot
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - chatbot_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - chatbot_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  chatbot_network:
    driver: bridge