# Generated by Django 5.2.12 on 2026-03-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='categorias',
        ),
        migrations.AddField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='documento',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
