# Generated by Django 5.2.12 on 2026-04-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_documento_categorias_documento_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='data_conversa',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='horario_conversa',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
