# Generated by Django 5.2.12 on 2026-04-04 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_conversa_data_conversa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilDeAcesso',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_perfil', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='data_conversa',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='horario_conversa',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='chatbot.perfildeacesso'),
        ),
        migrations.DeleteModel(
            name='PerfilAcesso',
        ),
    ]
