# Generated by Django 5.2.12 on 2026-04-05 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_perfildeacesso_remove_usuario_id_usuario_id_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='categorias',
            field=models.ManyToManyField(through='chatbot.CategoriaDocumento', to='chatbot.categoria'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='texto_resposta',
            field=models.TextField(default='Sem resposta cadastrada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversa',
            name='avaliacao',
            field=models.IntegerField(blank=True, choices=[(1, 'Bom'), (0, 'Ruim')], null=True),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='tempo_resposta',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DocumentoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.documento')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.categoria')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.IntegerField(default=1)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.pergunta')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.resposta')),
            ],
        ),
        migrations.CreateModel(
            name='VariacaoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_variacao', models.TextField()),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='chatbot.pergunta')),
            ],
        ),
    ]
