# Generated by Django 5.2.12 on 2026-04-05 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_documento_categorias_resposta_texto_resposta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('modelo', models.CharField(max_length=100)),
                ('custo', models.DecimalField(decimal_places=4, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perguntacategoria',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='perguntacategoria',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='perguntaresposta',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='perguntaresposta',
            name='resposta',
        ),
        migrations.RemoveField(
            model_name='variacaopergunta',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='id',
        ),
        migrations.RemoveField(
            model_name='conversa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='arquivo',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='id',
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='conversa',
            name='id_conversa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='id_documento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='id_pergunta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='resposta',
            name='id_resposta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='avaliacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.perfildeacesso'),
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id_chunk', models.AutoField(primary_key=True, serialize=False)),
                ('conteudo', models.TextField()),
                ('ordem', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chatbot.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Exportacao',
            fields=[
                ('id_exportacao', models.AutoField(primary_key=True, serialize=False)),
                ('chatbot', models.IntegerField()),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.conversa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='GerenciadorDialogo',
            fields=[
                ('id_gerenciador', models.AutoField(primary_key=True, serialize=False)),
                ('id_base', models.IntegerField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.documento')),
            ],
        ),
        migrations.AddField(
            model_name='conversa',
            name='gerenciador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.gerenciadordialogo'),
        ),
        migrations.CreateModel(
            name='VersaoDocumento',
            fields=[
                ('id_versao', models.AutoField(primary_key=True, serialize=False)),
                ('numero_versao', models.IntegerField()),
                ('conteudo', models.TextField()),
                ('data_versao', models.DateField(auto_now_add=True)),
                ('autor_alteracao', models.CharField(max_length=100)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.documento')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentoPergunta',
        ),
        migrations.DeleteModel(
            name='PerguntaCategoria',
        ),
        migrations.DeleteModel(
            name='PerguntaResposta',
        ),
        migrations.DeleteModel(
            name='VariacaoPergunta',
        ),
    ]
