# Generated by Django 5.2.12 on 2026-04-05 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_token_remove_perguntacategoria_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='avaliacao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='data_conversa',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='gerenciador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.gerenciadordialogo'),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='horario_conversa',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='pergunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.pergunta'),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='resposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.resposta'),
        ),
    ]
