# Generated by Django 5.2.12 on 2026-04-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_remove_usuario_perfil_usuario_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='vetor',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
