# Generated by Django 5.2.12 on 2026-05-21 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_documento_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversa',
            name='pergunta',
        ),
        migrations.RemoveField(
            model_name='conversa',
            name='resposta',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='conversa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='chatbot.conversa'),
        ),
    ]
