# Generated by Django 5.2.12 on 2026-05-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_remove_conversa_pergunta_remove_conversa_resposta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_modificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
