# Generated by Django 5.2.12 on 2026-05-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_alter_documento_data_modificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='data_modificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
